name: Create tag

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
        
      # uses https://github.com/marketplace/actions/publish-nuget that build, pack & publish 
      # nuget packages automatically when a project version is updated
      - name: push tag
        run: |
          tag=3.0.0
          git tag v$tag
          git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" v$tag